kind: pipeline
type: docker
name: node16

platform:
  os: linux

steps:
  - name: test
    image: node:16
    commands:
      - npm install
      - ./node_modules/pm2/bin/pm2 --name Test start npm -- start 
      - sleep 120
      - npm test
      - ./node_modules/pm2/bin/pm2 --name Test stop all
services:
  - name: postgesql
    image: postgresql:latest
    environment: 
      POSTGRES_USER: rapidapi_adm
      POSTGRES_PASSWORD: rapidapi
      POSTGRES_DB: rapidapi_adm
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - PGPASSWORD=rapidapi psql -a -h postgresql --user rapidapi_adm rapidapi_adm -c "CREATE SEQUENCE quota_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
        CREATE TABLE quota (
            id bigint DEFAULT nextval('quota_id_seq'::regclass) NOT NULL PRIMARY KEY,
            quota character varying(255) NOT NULL UNIQUE,
            author character varying(255) NOT NULL,
            created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
        ); 
        INSERT INTO quota (quota, author) VALUES ('There are only two kinds of languages - the ones people complain about and the ones nobody uses.', 'Bjarne Stroustrup'), 
         ('Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler'), 
          ('First, solve the problem. Then, write the code.', 'John Johnson'), 
          ('Java is to JavaScript what car is to Carpet.', 'Chris Heilmann'), 
          ('Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 'John Woods'), 
          ('I''m not a great programmer; I''m just a good programmer with great habits.', 'Kent Beck'), 
          ('Truth can only be found in one place - the code.', 'Robert C. Martin'), 
          ('If you have to spend effort looking at a fragment of code and figuring out what it''s doing, then you should extract it into a function and name the function after the "what".', 'Martin Fowler'), 
          ('The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil (or at least most of it) in programming.', 'Donald Knuth'), 
        ('SQL, Lisp, and Haskell are the only programming languages that I’ve seen where one spends more time thinking than typing.', 'Philip Greenspun'), 
        ('Deleted code is debugged code.', 'Jeff Sickel'), 
        ('There are two ways of constructing a software design - One way is to make it so simple that there are obviously no deficiencies and the other way is to make it so complicated that there are no obvious deficiencies.', 'C.A.R. Hoare'), 
        ('Simplicity is prerequisite for reliability.', 'Edsger W. Dijkstra'), 
        ('There are only two hard things in Computer Science - cache invalidation and naming things.', 'Phil Karlton'), 
        ('Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'Bill Gates'), 
        ('Controlling complexity is the essence of computer programming.', 'Brian Kernighan'),
        ('The only way to learn a new programming language is by writing programs in it.', 'Dennis Ritchie')"